---
output: github_document
bibliography: "../research/gerard_bib.bib"
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

I have written a lot of code for my research. You can see most of it on my [GitHub Page](https://github.com/dcgerard). But here is a list of some of my packages:

- [ldsep](https://cran.r-project.org/package=ldsep): Linkage Disequilibrium Shrinkage Estimation for Polyploids
- [hwep](https://cran.r-project.org/package=hwep): Hardy-Weinberg Equilibrium in Polyploids
- [updog](https://cran.r-project.org/package=updog): Flexible Genotyping for Polyploids
- [tensr](https://cran.r-project.org/package=tensr): Covariance Inference and Decompositions for Tensor Datasets
- [seqgendiff](https://cran.r-project.org/package=seqgendiff): RNA-Seq Generation/Modification for Simulation
- [hose](https://github.com/dcgerard/hose): Higher-Order Spectral Estimators
- [vicar](https://github.com/dcgerard/vicar): Various Ideas for Confounder Adjustment in Regression


Most of my work emphasizes extreme reproducibility, linking code with data, and executing automatically via a Makefile.

- @gerard2021double: <https://github.com/dcgerard/hwesims>
- @gerard2021pairwise: <https://github.com/dcgerard/ld_simulations>
- @gerard2021scalable: <https://github.com/dcgerard/ldfast_sims>
- @gerard2021unifying: <https://github.com/dcgerard/ruvb_sims>
- @gerard2020data: <https://github.com/dcgerard/reproduce_fasims>
- @gerard2020empirical: <https://github.com/dcgerard/mouthwash_sims>
- @gerard2020priors: <https://github.com/dcgerard/reproduce_prior_sims>
- @gerard2018genotyping: <https://github.com/dcgerard/reproduce_genotyping>
- @gerard2017adaptive: <https://github.com/dcgerard/reproduce_sure>

# References
